
export enum ErrorCode {
    MISSING_REQUIRED_QUERY_PARAMETER = 'MISSING_REQUIRED_QUERY_PARAMETER',
    REPOSITORY_NOT_FOUND = 'REPOSITORY_NOT_FOUND',
    FILE_NOT_FOUND = 'FILE_NOT_FOUND',
    INVALID_REQUEST_BODY = 'INVALID_REQUEST_BODY',
}
