name: Deploy Demo

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-demo:
    uses: ./.github/workflows/_gcp-deploy.yml
    secrets: inherit
    permissions:
      contents: 'read'
      # Requird for OIDC auth with GCP.
      # @see: https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
      id-token: 'write'
    with:
      environment: demo
