
export enum ErrorCode {
    UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
    MISSING_REQUIRED_QUERY_PARAMETER = 'MISSING_REQUIRED_QUERY_PARAMETER',
    REPOSITORY_NOT_FOUND = 'REPOSITORY_NOT_FOUND',
    FILE_NOT_FOUND = 'FILE_NOT_FOUND',
    INVALID_REQUEST_BODY = 'INVALID_REQUEST_BODY',
    NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',
    NOT_FOUND = 'NOT_FOUND',
    CONNECTION_SYNC_ALREADY_SCHEDULED = 'CONNECTION_SYNC_ALREADY_SCHEDULED',
}
