
export enum ErrorCode {
    UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
    MISSING_REQUIRED_QUERY_PARAMETER = 'MISSING_REQUIRED_QUERY_PARAMETER',
    REPOSITORY_NOT_FOUND = 'REPOSITORY_NOT_FOUND',
    FILE_NOT_FOUND = 'FILE_NOT_FOUND',
    INVALID_REQUEST_BODY = 'INVALID_REQUEST_BODY',
    SELF_INVITE = 'SELF_INVITE',
    NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',
    NOT_FOUND = 'NOT_FOUND',
    CONNECTION_SYNC_ALREADY_SCHEDULED = 'CONNECTION_SYNC_ALREADY_SCHEDULED',
    ORG_DOMAIN_ALREADY_EXISTS = 'ORG_DOMAIN_ALREADY_EXISTS',
    ORG_INVALID_SUBSCRIPTION = 'ORG_INVALID_SUBSCRIPTION',
    MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    MEMBER_NOT_OWNER = 'MEMBER_NOT_OWNER',
}
