// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  negate = 24,
  Program = 1,
  OrExpr = 2,
  AndExpr = 3,
  NegateExpr = 4,
  PrefixExpr = 5,
  ParenExpr = 19,
  Term = 20
