name: Changelog Reminder

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: mskelton/changelog-reminder-action@v3