name: Release Sourcebot (Cloud - Production)

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  workflow_dispatch:

concurrency:
  group: release-cloud-prod-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/_build-cloud.yml
    with:
      environment: prod
      git_ref: ${{ github.ref }}
      docker_tags: |
        type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
        type=sha,format=long,enable=${{ github.ref == 'refs/heads/main' }}
        type=semver,pattern=v{{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
        type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
    secrets: inherit
