name: Scratch Workflow

on:
  push:
    branches: [bkellam/release_cleanup]
  workflow_dispatch:

jobs:
  scratch:
    uses: ./.github/workflows/_gcp-deploy.yml
    permissions:
      contents: 'read'
      # Requird for OIDC auth with GCP.
      # @see: https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
      id-token: 'write'
    with:
      environment: staging
